name: Monorepo Multi-Project CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ] # Déclenche les tests lors du merge vers develop

jobs:
  build:
    name: Build & Test - ${{ matrix.project_name }}
    runs-on: ubuntu-latest # Utilise une machine Linux virtuelle

    strategy:
      fail-fast: false # Empêche qu'un projet en échec n'arrête les tests des autres
      matrix:
        include:
          # --- Lister les projets ici ---
          - project_path: "Java-11/mini-projects/multithread-chat-server"
            project_name: "Multithread-Chat-Server"
            java_version: "11"


    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Configurer le JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin' # Distribution stable et recommandée
          cache: maven           # Accélère les builds futurs en cachant les dépendances

      - name: 3.1 Exécuter les Tests Unitaires
        run: mvn test -Dgroups="unit" --batch-mode --file ${{ matrix.project_path }}/pom.xml

      - name: 3.2 Exécuter les Smoke Tests
        run: mvn test -Dgroups="smoke" --batch-mode --file ${{ matrix.project_path }}/pom.xml

      # 'verify' lance failsafe et vérifie le respect des seuils
      # On saute les tests unitaires déjà faits pour gagner du temps
      - name: 3.3 Exécuter les Tests d'Intégration
        run: mvn verify -Dgroups="integration" -DskipUnitTests=true --batch-mode --file ${{ matrix.project_path }}/pom.xml

      - name: 3.4 Génération du rapport de test
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.project_name }}
          path: ${{ matrix.project_path }}/target/surefire-reports/

      # On utilise 'package' au lieu de 'clean package' pour garder
      # les résultats des étapes précédentes si nécessaire.
      - name: 4. Vérifier la compilation (Build) et générer le package (JAR)
        run: mvn package -DskipTests --batch-mode --file ${{ matrix.project_path }}/pom.xml

      # Cette étape rend le JAR disponible dans l'interface GitHub
      - name: 5. Téléverser l'artefact JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project_name }}-executable  # Le chemin pointe vers le dossier target généré par Maven
          path: ${{ matrix.project_path }}/target/*.jar
          retention-days: 5  # Optionnel : supprime l'artefact après 5 jours pour gagner de la place